version: "2"
services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"

  mongo:
    image: "bitnami/mongodb:latest"
    volumes:
      - "mongodb_master_data:/bitnami"
    env_file:
      - ./server/.env
    ports:
      - 27017:27017
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes: 
      - ./server/config:/app/config
      - ./server/controllers:/app/controllers
      - ./server/router:/app/router
      - ./server/models:/app/models
      - ./server/index.js:/app/index.js
      - ./server/constants.js:/app/constants.js 
    ports: 
      - "3000:3000"
    links:
      - "mongo:mongo"
    restart: always
    depends_on:
      - mongo

  elastic:
    image: "bitnami/elasticsearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    volumes:
      - "elasticsearch_data:/bitnami"

  mongo-backup:
    image: "istepanov/mongodump:3.4"
    volumes:
      - mongo-backup:/backup
    environment:
      CRON_SCHEDULE: "0 1 * * *"
    depends_on:
      - mongo

volumes:
  mongodb_master_data:
    driver: local
  mongo-backup:
    driver: local
  elasticsearch_data:
    driver: local
