version: '2'
services:
  mongo:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_master_data:/bitnami'
    env_file:
      - ./server/.env
    ports:
      - 27017:27017
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes: 
      - ./server/config:/app/config
      - ./server/controllers:/app/controllers
      - ./server/router:/app/router
      - ./server/models:/app/models
      - ./server/index.js:/app/index.js
      - ./server/constants.js:/app/constants.js 
    ports: 
      - "3000:3000"
    links:
      - "mongo:mongo"
    restart: always
    depends_on:
      - mongo

  mongo-backup:
    image: "istepanov/mongodump:3.4"
    volumes:
      - mongo-backup:/backup
    environment:
      CRON_SCHEDULE: '0 1 * * *'
    depends_on:
      - mongo

volumes:
  mongodb_master_data:
    driver: local
  mongo-backup:
    driver: local
