version: "2"
services: 
    mongo:
        image: mongo
        ports: 
            - '27017:27017'
    web:
        build: .
        ports: 
            - '8080:8080'
        working_dir: '/builtright'
        command: npm run start
        environment: 
            - EXPRESS_PORT=8080
            - APP_SECRET=Ra07xv07qjxcvkjajv8c7cq978xfibhkn45jhdoxcb7w
        volumes: 
            - .:/builtright
        links: 
            - mongo
        
