version: '2'

services:
  mongo:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_master_data:/bitnami'
    env_file:
      - ./server/.env
    ports:
      - 27017:27017

        #  elasticsearch:
        #    image: 'bitnami/elasticsearch:latest'
        #    volumes:
        #      - 'elasticsearch_master_data:/bitnami/elasticsearch'
        #    ports:
        #      - 9200:9200
        #      - 9300:9300

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes: 
      - ./server/config:/app/config
      - ./server/controllers:/app/controllers
      - ./server/router:/app/router
      - ./server/models:/app/models
      - ./server/index.js:/app/index.js
      - ./server/constants.js:/app/constants.js 
    ports: 
      - "3000:3000"
    links:
      - "mongo:mongo"
        # - "elasticsearch:elasticsearch"
    restart: always
    depends_on:
      # - elasticsearch
      - mongo

  gui:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    links:
      - "server:server"
    restart: always

  ghost:
    image: ghost:1-alpine
    ports:
      - "3001:2368"
    volumes:
      - /opt/builtright/blog:/var/lib/ghosts
    restart: always

volumes:
  mongodb_master_data:
    driver: local
  elasticsearch_master_data:
    driver: local
