version: '2'

services: 
  server:
    volumes: 
      - ./server/config:/app/config
      - ./server/controllers:/app/controllers
      - ./server/router:/app/router
      - ./server/models:/app/models
      - ./server/index.js:/app/index.js
      - ./server/constants.js:/app/constants.js
