version: '2'
services: 
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env.docker
    links:
      - mongo:mongo
      - redis:redis

  mongo:
    image: bitnami/mongodb
    ports: 
      - "27017:27017"
    env_file:
      - ./server/.env.docker

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "443:443"
      - "80:80"
    links:
      - server:server
    env_file:
      - ./client/.env.docker