version: '2'
services: 
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./server/models:/app/models"
      - "./server/controllers:/app/controllers"
      - "./server/config:/app/config"
      - "./server/package.json:/app/package.json"
      - "./server/index.js:/app/index.js"
      - "./server/router.js:/app/router.js"
      - "./server/socketEvents.js:/app/socketEvents.js"
      - "./server/logger.js:/app/logger.js"
      - "./server/constants.js:/app/constants.js"
      - "./server/helpers.js:/app/helpers.js"
    env_file:
      - ./server/.env.docker
    links:
      - mongo:mongo
      - redis:redis

  mongo:
    image: bitnami/mongodb
    ports: 
      - "27017:27017"
    env_file:
      - ./server/.env.docker

  redis:
    image: redis
    ports:
      - "6379:6379"

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "443:443"
      - "80:80"
    links:
      - server:server
    env_file:
      - ./client/.env.docker