version: '2'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_master_data:/bitnami'
    env_file:
      - ./server/.env

volumes:
  mongodb_master_data:
    driver: local
