version: '2'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_master_data:/bitnami'
    env_file:
      - ./server/.env

  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    volumes:
      - 'elasticsearch_master_data:/bitnami/elasticsearch'
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  mongodb_master_data:
    driver: local
  elasticsearch_master_data:
    driver: local
