version: '2'
services: 
  server:
    image: hivemindapps/builtright-server:latest 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production 
    links:
      - mongo:mongo
      - redis:redis

  web:
    image: hivemindapps/builtright-client:latest 
    ports: 
      - "80:80"
      - "443:443"
    links: 
      - server:server
    environment:
      - NODE_ENV=production
      - API_URL=server:3000

  mongo:
    image: bitnami/mongodb
    ports: 
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"
