version: '2'
services: 
  server:
    image: hivemindapps/builtright-server:latest 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production 
    links:
      - mongo:mongo
    depends_on:
      - mongo

  web:
    image: hivemindapps/builtright-client:latest 
    ports: 
      - "8080:80"
    links: 
      - server:server
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - API_URL=server:3000

  mongo:
    image: bitnami/mongodb
    ports: 
      - "27017:27017"
    env_file:
      - ./server/.env
