version: '2'

services: 
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env.docker

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    links:
      - server:server
    env_file:
      - ./client/.env.docker

